# Use an official Node.js runtime as a parent image
FROM node:lts-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install dependencies
RUN npm install

COPY tsconfig.json ./

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 for the Express server to listen on
EXPOSE 3000

# Start the Express server
CMD [ "npm", "start" ]
